// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TemperatureDbContext))]
    [Migration("20251001211020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Formato", b =>
                {
                    b.Property<int>("FormatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatoId"));

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDescongelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RealizadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormatoId");

                    b.ToTable("Formatos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Registro", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroId"));

                    b.Property<string>("CodigoProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormatoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HoraFinConsumo")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicioConsumo")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraInicioDescongelado")
                        .HasColumnType("time");

                    b.Property<string>("NumeroCoche")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemperaturaProducto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RegistroId");

                    b.HasIndex("FormatoId");

                    b.ToTable("Registros", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Registro", b =>
                {
                    b.HasOne("Domain.Entities.Formato", "Formato")
                        .WithMany("Registros")
                        .HasForeignKey("FormatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formato");
                });

            modelBuilder.Entity("Domain.Entities.Formato", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
